repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: "pip3 freeze > requirements.txt; git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: git
        name: git
        entry: "git add ."
        language: system
        pass_filenames: false
        stages: [commit]
